### ISSUE TITLE
Replace Rails.Error with Rails.Result union type?

### ISSUE THREAD

**Issue by avh4** [NoRedInk/elm-rails#19]
The `Rails.Error` type is messy to work with due to all the nesting, and is also frequently wrapping in a `Result` in any case (see `decodeErrors` returns `Result (Rails.Error e) a`).

I think this would be more straightforward to work with if `type alias Error` were removed and replaced with something like

```elm
type Result x a    -- would be fine with better variable names if suggested
    = Ok a
    | AppErr Http.Error x
    | HttpErr Http.Error
```

**Comment by BrianHicks** [comment]
fixed! It looks like this now:

```elm
type Response error success
    = Success success
    | HttpError Http.Error
    | AppError Http.Metadata error
```
