### ISSUE TITLE
Example project?

### ISSUE THREAD

**Issue by andyrue** [NoRedInk/elm-rails#8]
I'm very new to Elm and wanting to interact with my Rails API. I've been staring at this for days trying to figure out how to make it work but can't seem to put it together by looking at the `hats` snippets in the documentation. I'm really wishing somebody smarter than myself could put together a very simple example of performing a `get` and a `post` for a simple item using this module.

The biggest void in my understanding is how to make a `ResponseDecoder`. 

Referring to the GET sample, it's unclear to me what's going on in the `hats` function in the documentation.

```
Send a GET request to the given URL. You also specify how to decode the response.
import Json.Decode (list, string)
hats : String -> Task (Error (List String)) (List String)
hats authToken =
    get (decoder (list string) (succeed ())) "http://example.com/hat-categories.json"
```

 From my limited understanding I see from the Type Annotation that  `hats` takes a `String` argument and returns a `Task (Error (List String)) (List String)`. Then in the function it takes the string `authToken` and runs a get request, however I don't see the `authToken` string ever being used, so why is it being passed in?

Anyway, any help and guidance is greatly appreciated. Thanks!

**Comment by eeue56** [comment]
Have a look at this example -

``` elm
module Component.Account.Login.Requests where

import Task exposing (Task)
import Http

import Json.Encode as Encode
import Json.Decode as Decode

import Rails

import Component.Account.Login.Model exposing (loginUrl)
import Component.Account.Login.Requests.Model exposing (RailsErrors)

{-| Attempt a log in.

    Takes a rails authToken, username, and password.
    Note that username could be a username or an email.

    On server error, produce a `Http.Error`
    On login error, produce a list of `(a, String)` tuples
-}
attemptLogin : String -> String -> String -> Decode.Decoder (RailsErrors field) -> Task (Rails.Error (RailsErrors field)) (RailsErrors field)
attemptLogin authToken username password decoder =
    let
        body =
            Encode.encode 0 <|
                Encode.object
                    [ ( "login_name", Encode.string username )
                    , ( "password", Encode.string password )
                    ]
    in
        Rails.post
            authToken
            (Rails.always decoder)
            loginUrl
            (Http.string body)
```

That hats example is broken

**Comment by andyrue** [comment]
And an example of using the `attemptLogin` function would be.

`attemptLogin "authtoken" "user@example.com" "password123" decoder` but where does the `decoder` come from? Do you have an example of what a decoder looks like? 

```
decoder : Decoder value -> Decoder error -> ResponseDecoder error value
decoder successDecoder failureDecoder =
  ResponseDecoder successDecoder failureDecoder
```

But what does that look like in real life? :-) Thank you for your patience.

**Comment by eeue56** [comment]
``` elm
decodeServerErrors =
    Rails.Decode.errors <|
        Dict.fromList
            [ ("edmodo", Edmodo)
            , ("base", General)
            , ("password", Ignore)
            , ("login_name", Ignore)
            , ("first_name", Ignore)
            , ("last_name", Ignore)
            , ("username", Ignore)
            ]
```

hope that helps :)

**Comment by andyrue** [comment]
Thank you, it's becoming a bit more clear. I think I almost have it. This is what I have.

```
type Field = Name | ID

mappings = 
  Dict.fromList
      [ 
        ("name", Name),
        ("id", ID)
      ]
```

And my GET looks like this.

```
port runner : Task (Rails.Error (Rails.Decode.ErrorList Field)) (List ( Field, String ))
port runner =
  Rails.get "" (Rails.always (Rails.Decode.errors mappings))  "http://localhost:3000/api/departments"
```

That actually is making a request to the server, woot! But....it's sending an OPTIONS request instead of a GET request. Why might that be?

**Comment by eeue56** [comment]
I _think_ you need the authToken to be the actual authToken, otherwise rails doesn't know what to do. You can grab it by doing `var csrfTokenNode = document.head.querySelector('meta[name="csrf-token"]');`

Then send the content of `csrfTokenNode` to Elm through a port

**Comment by andyrue** [comment]
Ah, thanks. I was wondering if it was the authToken...I thought Rails only needed it for requests that changed data, but that makes sense. I'm so used to taking the authToken handling for granted. You've been immensely helpful. I'll see if I can get that going. Thank you!

**Comment by andyrue** [comment]
Ok, I don't think it's a CSRF thing. I'm using Rails 5 in API mode which apparently by default disables CSRF checking. I verified that `protect_from_forgery` is not in the `ApplicationController` or anywhere else. I'll keep digging.

**Comment by andyrue** [comment]
Anybody else running into this, the problem is with CORS. An OPTIONS request is sent first and then the real request is sent after a valid response. Using the [rack-cors](https://github.com/cyu/rack-cors) gem solved it for me.

**Comment by eeue56** [comment]
@andyrue Thanks for posting your solution here! Is there a way to get this library to work without needing rack-cors?

**Comment by andyrue** [comment]
The way around it without rack-cors would probably be to do something like suggested in [this blog post](http://blog.rudylee.com/2013/10/29/rails-4-cors/).
